/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_BASIC_U_H
#define EDGER8R_BASIC_U_H

#include <openenclave/host.h>

#include "basic_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_basic_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t enc_hello(
    oe_enclave_t* enclave,
    int* _retval,
    const char* msg,
    int* out_val);

/**** OCALL prototypes. ****/
int host_hello(
    const char* msg,
    int* out_val);

OE_EXTERNC_END

#endif // EDGER8R_BASIC_U_H
