/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_BASIC_T_H
#define EDGER8R_BASIC_T_H

#include <openenclave/enclave.h>

#include "basic_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int enc_hello(
    const char* msg,
    int* out_val);

/**** OCALL prototypes. ****/
oe_result_t host_hello(
    int* _retval,
    const char* msg,
    int* out_val);

OE_EXTERNC_END

#endif // EDGER8R_BASIC_T_H
